package com.demo.transaction.model;

import java.util.Date;

public class SkyAnimal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sky_animal.id
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sky_animal.sky_animal_name
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    private String skyAnimalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sky_animal.update_time
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sky_animal.create_time
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sky_animal.id
     *
     * @return the value of sky_animal.id
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sky_animal.id
     *
     * @param id the value for sky_animal.id
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sky_animal.sky_animal_name
     *
     * @return the value of sky_animal.sky_animal_name
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    public String getSkyAnimalName() {
        return skyAnimalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sky_animal.sky_animal_name
     *
     * @param skyAnimalName the value for sky_animal.sky_animal_name
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    public void setSkyAnimalName(String skyAnimalName) {
        this.skyAnimalName = skyAnimalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sky_animal.update_time
     *
     * @return the value of sky_animal.update_time
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sky_animal.update_time
     *
     * @param updateTime the value for sky_animal.update_time
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sky_animal.create_time
     *
     * @return the value of sky_animal.create_time
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sky_animal.create_time
     *
     * @param createTime the value for sky_animal.create_time
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}