package com.demo.transaction.dao;

import com.demo.transaction.model.SkyAnimal;

public interface SkyAnimalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sky_animal
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    int insert(SkyAnimal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sky_animal
     *
     * @mbg.generated Thu Mar 26 18:10:18 CST 2020
     */
    int insertSelective(SkyAnimal record);
}